import { MessageType } from "@/app/home-type";

export const tempMessage:MessageType = {
    message: `**Retro Funding 4: Unlocking the Potential of Onchain Builders on Optimism**\n\nThe Optimism Collective is proud to announce the launch of Retro Funding 4, a groundbreaking initiative designed to reward onchain builders for their invaluable contributions to the success of Optimism. This round of Retroactive Public Goods Funding (Retro Funding) aims to expand the reach and impact of the network by incentivizing developer growth and increased network activity.\n\n**What is Retro Funding 4?**\n\nRetro Funding 4 is a round of Retro Funding that will allocate 10 million OP tokens to onchain builders who have deployed contracts to the Superchain and contributed to the success of Optimism. The OP token allocation for Retro Funding 4 is designed to reflect the impact generated by onchain builders, as well as set a strong incentive for the continuous generation of demand for Optimism blockspace.\n\n**Key Objectives of Retro Funding 4**\n\nThe primary objectives of Retro Funding 4 are:\n\n1. **Incentivize Developer Growth**: Reward onchain builders for their contributions to the success of Optimism, encouraging them to continue building and innovating on the network.\n2. **Increase Network Activity**: Stimulate increased network activity by incentivizing developers to deploy contracts to the Superchain and utilize Optimism blockspace.\n3. **Expand the Reach and Impact of the Network**: Foster a thriving ecosystem of onchain builders, contributing to the growth and adoption of Optimism.\n\n**Application Guidelines and Voting Experience**\n\nTo participate in Retro Funding 4, projects must apply via retrofunding.optimism.io. All projects must create an Optimist Profile, which serves as a builder's persistent identity across the Collective. The application guidelines can be found on the Optimism governance forum.\n\nThe voting app for Round 4 is available, and badgeholders can find all relevant information for voting in the Badgeholder Manual.\n\n**Future of Retro Funding**\n\nRetro Funding 4 is part of the Retro Funding experiment, which aims to reward onchain builders for their contributions to the success of Optimism. The Foundation will size Retro Funding 4 & 5, and will propose round sizes for Retro Funding 6 & 7, to be ratified by the Citizens’ House. In the future, this process will gradually transition to be more community-led, which may involve the creation of a Budget Board or similar entity in future Seasons.\n\n**Conclusion**\n\nRetro Funding 4 is a significant milestone in the growth and development of the`,
    role: "assistant",
    links: [
        "https://gov.optimism.io/t/7988",
        "https://gov.optimism.io/t/8239",
        "https://community.optimism.io/citizens-house/rounds/retropgf-4",
        "https://gov.optimism.io/t/8200",
        "https://gov.optimism.io/t/8165",
        "https://gov.optimism.io/t/8437",
        "https://gov.optimism.io/t/8013",
        "https://gov.optimism.io/t/8138"
    ],
    status:"success",
}
